"""Module 7 — Attendance & Gate Verification: serializers."""

from __future__ import annotations

import uuid

from rest_framework import serializers

from .models import (
    AttendanceEvent,
    Decision,
    Direction,
    GatePass,
    RegisterScan,
    VerificationMethod,
)


class GatePassSerializer(serializers.ModelSerializer):
    """Module 7.1 — the worker's own QR credential.

    ``code`` is the QR payload. Only ever returned to the worker it belongs to
    and to gate staff of their society; it is the thing that opens a gate.
    """

    worker_name = serializers.CharField(source="worker.user.get_full_name", read_only=True)
    is_usable = serializers.BooleanField(read_only=True)

    class Meta:
        model = GatePass
        fields = [
            "code",
            "worker",
            "worker_name",
            "is_active",
            "is_usable",
            "issued_at",
            "revoked_at",
            "revoked_reason",
            "rotation_count",
        ]
        read_only_fields = fields


class AttendanceEventSerializer(serializers.ModelSerializer):
    """The audit record. Read-only everywhere — history is never edited."""

    worker_name = serializers.CharField(source="worker.user.get_full_name", read_only=True)
    worker_photo = serializers.ImageField(source="worker.photo", read_only=True)
    gate_name = serializers.CharField(source="gate.name", read_only=True, default=None)
    recorded_by_name = serializers.CharField(
        source="recorded_by.get_full_name", read_only=True, default=None
    )
    overridden_by_name = serializers.CharField(
        source="overridden_by.get_full_name", read_only=True, default=None
    )
    needs_review = serializers.BooleanField(read_only=True)
    was_overridden = serializers.BooleanField(read_only=True)
    sync_delay_seconds = serializers.FloatField(read_only=True)

    class Meta:
        model = AttendanceEvent
        fields = [
            "id",
            "worker",
            "worker_name",
            "worker_photo",
            "gate",
            "gate_name",
            "recorded_by",
            "recorded_by_name",
            "direction",
            "method",
            "decision",
            "decision_reason",
            "engagement",
            "booking",
            "was_expected",
            "occurred_at",
            "recorded_at",
            "sync_delay_seconds",
            "face_checked",
            "face_match_score",
            "face_verified",
            "overridden_by",
            "overridden_by_name",
            "override_reason",
            "overridden_at",
            "needs_review",
            "was_overridden",
            "device_id",
            "was_offline",
        ]
        read_only_fields = fields


class ScanLookupSerializer(serializers.Serializer):
    """A scanned QR payload."""

    code = serializers.UUIDField()


class ExpectedVisitSerializer(serializers.Serializer):
    """One visit the worker is due for, as the guard sees it."""

    source = serializers.CharField(read_only=True)
    source_id = serializers.IntegerField(read_only=True)
    title = serializers.CharField(read_only=True)
    start_time = serializers.TimeField(read_only=True)
    end_time = serializers.TimeField(read_only=True)
    flat_label = serializers.CharField(read_only=True)
    is_confirmed = serializers.BooleanField(read_only=True)


class GateRosterEntrySerializer(serializers.Serializer):
    """One worker on the day's roster, with the code that identifies them.

    ``pass_code`` is what opens a gate, which is why this shape is only ever
    served to gate staff of that society.
    """

    worker_id = serializers.IntegerField(read_only=True)
    worker_name = serializers.CharField(read_only=True)
    pass_code = serializers.CharField(read_only=True, allow_null=True)
    visits = ExpectedVisitSerializer(many=True, read_only=True)


class ScanResultSerializer(serializers.Serializer):
    """What a scan tells the guard. Creates nothing — see services.look_up_pass."""

    worker_id = serializers.IntegerField(read_only=True)
    worker_name = serializers.CharField(read_only=True)
    worker_photo = serializers.CharField(read_only=True, allow_null=True)
    is_usable = serializers.BooleanField(read_only=True)
    reason = serializers.CharField(read_only=True, allow_blank=True)
    is_expected = serializers.BooleanField(read_only=True)

    # The server's suggestion. SRS 3.7 gives the guard the actual call.
    recommendation = serializers.ChoiceField(choices=Decision.choices, read_only=True)
    expected_visits = ExpectedVisitSerializer(many=True, read_only=True)


class RecordEventSerializer(serializers.Serializer):
    """The guard logs what they decided (Modules 7.2, 7.5, 7.6).

    ``id`` is generated by the *device*, not the server. That is what makes a
    retried submission idempotent, so it is required rather than optional — a
    server-generated id would defeat the entire offline design.
    """

    id = serializers.UUIDField(default=uuid.uuid4)
    worker = serializers.IntegerField()
    direction = serializers.ChoiceField(choices=Direction.choices, default=Direction.ENTRY)
    method = serializers.ChoiceField(
        choices=VerificationMethod.choices, default=VerificationMethod.QR
    )
    decision = serializers.ChoiceField(choices=Decision.choices, default=Decision.ALLOWED)
    decision_reason = serializers.CharField(
        required=False, allow_blank=True, default="", max_length=200
    )
    occurred_at = serializers.DateTimeField()
    gate = serializers.IntegerField(required=False, allow_null=True)
    device_id = serializers.CharField(
        required=False, allow_blank=True, default="", max_length=64
    )
    was_offline = serializers.BooleanField(default=False)

    def validate_decision_reason(self, value):
        return value.strip()

    def validate(self, attrs):
        if attrs["decision"] == Decision.DENIED and not attrs.get("decision_reason"):
            # A denial without a reason is unauditable, and the person turned
            # away deserves to know why.
            raise serializers.ValidationError(
                {"decision_reason": "Say why entry was refused."}
            )
        return attrs


class SelfCheckInSerializer(serializers.Serializer):
    """Module 13.3 tier 2 — a worker recording their own arrival.

    ``id`` is device-generated for the same reason it is on
    :class:`RecordEventSerializer`: this is a queueable event, and a worker who
    taps "I have arrived" with no signal must be able to retry without creating
    a second record.

    Position is optional. A phone with location switched off still produces a
    usable record — it just goes to an administrator rather than standing on its
    own. Refusing the check-in outright would leave a worker who did the job
    with no evidence of it, which is the failure this tier exists to prevent.
    """

    id = serializers.UUIDField(default=uuid.uuid4)
    direction = serializers.ChoiceField(
        choices=Direction.choices, default=Direction.ENTRY
    )
    occurred_at = serializers.DateTimeField()

    latitude = serializers.FloatField(required=False, allow_null=True)
    longitude = serializers.FloatField(required=False, allow_null=True)

    #: What the device says its own fix is worth, in metres. Honoured rather
    #: than ignored — a phone admitting to a 180 m fix is being truthful, and
    #: holding that against the person carrying it punishes them for standing
    #: next to a tall building.
    accuracy_metres = serializers.FloatField(required=False, allow_null=True)

    device_id = serializers.CharField(
        required=False, allow_blank=True, default="", max_length=64
    )
    was_offline = serializers.BooleanField(default=False)

    def validate(self, attrs):
        has_latitude = attrs.get("latitude") is not None
        has_longitude = attrs.get("longitude") is not None
        if has_latitude != has_longitude:
            raise serializers.ValidationError(
                {"latitude": "Send both latitude and longitude, or neither."}
            )
        return attrs


class SelfCheckInResultSerializer(serializers.Serializer):
    """What the worker is told. Deliberately explicit about the outcome.

    A check-in that needs review is not a failure and must not read like one —
    but nor may it read like a clean entry, because Module 8 bills differently
    from the two.
    """

    id = serializers.CharField(read_only=True)
    created = serializers.BooleanField(read_only=True)
    decision = serializers.CharField(read_only=True)
    decision_reason = serializers.CharField(read_only=True)
    was_expected = serializers.BooleanField(read_only=True)
    needs_review = serializers.BooleanField(read_only=True)
    distance_metres = serializers.FloatField(read_only=True, allow_null=True)
    location_checked = serializers.BooleanField(read_only=True)


class SyncRequestSerializer(serializers.Serializer):
    """Module 7.4 — a guard device replaying its offline queue."""

    events = RecordEventSerializer(many=True)

    def validate_events(self, value):
        if not value:
            raise serializers.ValidationError("Send at least one event.")
        if len(value) > 500:
            # Bounded so one device cannot exhaust a free-tier instance's
            # memory with a runaway queue.
            raise serializers.ValidationError(
                "Sync at most 500 events at a time."
            )
        return value


class SyncResultSerializer(serializers.Serializer):
    """Which ids landed, so the device knows exactly what to clear."""

    created = serializers.ListField(child=serializers.CharField(), read_only=True)
    duplicates = serializers.ListField(child=serializers.CharField(), read_only=True)
    rejected = serializers.ListField(child=serializers.DictField(), read_only=True)
    accepted_count = serializers.IntegerField(read_only=True)


class FaceCheckSerializer(serializers.Serializer):
    """Module 7.3 — a live photo taken at the gate."""

    photo = serializers.ImageField()


class FaceResultSerializer(serializers.Serializer):
    available = serializers.BooleanField(read_only=True)
    verified = serializers.BooleanField(read_only=True)
    score = serializers.FloatField(read_only=True, allow_null=True)
    engine = serializers.CharField(read_only=True, allow_blank=True)
    reason = serializers.CharField(read_only=True, allow_blank=True)
    needs_guard_review = serializers.BooleanField(read_only=True)


class OverrideSerializer(serializers.Serializer):
    """A guard resolves a below-threshold face match (Module 7.3).

    A reason is always required, in both directions. Overriding a biometric
    check — to let someone in or to keep them out — is exactly the decision that
    has to be answerable for later.
    """

    allow = serializers.BooleanField()
    reason = serializers.CharField(max_length=200)

    def validate_reason(self, value):
        if not value.strip():
            raise serializers.ValidationError("Say why you are overriding the check.")
        return value.strip()


class RegisterScanSerializer(serializers.ModelSerializer):
    """Module 7.5 — a photographed paper register."""

    uploaded_by_name = serializers.CharField(
        source="uploaded_by.get_full_name", read_only=True, default=None
    )
    gate_name = serializers.CharField(source="gate.name", read_only=True, default=None)

    class Meta:
        model = RegisterScan
        fields = [
            "id",
            "image",
            "for_date",
            "gate",
            "gate_name",
            "note",
            "uploaded_by",
            "uploaded_by_name",
            "transcribed",
            "transcribed_at",
            "created_at",
        ]
        read_only_fields = [
            "id", "uploaded_by", "uploaded_by_name", "gate_name",
            "transcribed", "transcribed_at", "created_at",
        ]
