# Generated by Django 5.2.16 on 2026-07-31 05:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_seed_service_categories'),
        ('hiring', '0001_initial'),
        ('societies', '0002_society_allow_resident_self_checkin_and_more'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=200)),
                ('rotation_count', models.PositiveSmallIntegerField(default=0)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gate_pass', to='workers.workerprofile')),
            ],
            options={
                'verbose_name': 'gate pass',
                'verbose_name_plural': 'gate passes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=10)),
                ('method', models.CharField(choices=[('qr', 'QR code scanned'), ('face', 'Face verified'), ('manual', 'Logged manually by the guard'), ('self_checkin', 'Worker checked in from the app'), ('register', 'Transcribed from the paper register')], max_length=20)),
                ('decision', models.CharField(choices=[('allowed', 'Allowed'), ('denied', 'Denied'), ('pending_review', "Needs the guard's decision")], db_index=True, default='allowed', max_length=20)),
                ('decision_reason', models.CharField(blank=True, max_length=200)),
                ('was_expected', models.BooleanField(default=False, help_text="Whether this matched something on the day's roster.")),
                ('occurred_at', models.DateTimeField(db_index=True, help_text="When it happened, from the guard's device.")),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the server received it.')),
                ('face_checked', models.BooleanField(default=False)),
                ('face_match_score', models.FloatField(blank=True, help_text='Similarity, 0-1. Null if not checked.', null=True)),
                ('face_verified', models.BooleanField(default=False)),
                ('face_photo', models.ImageField(blank=True, upload_to='attendance/faces/%Y/%m/')),
                ('override_reason', models.CharField(blank=True, max_length=200)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, help_text='Which guard device queued this, for reconciling a bad batch.', max_length=64)),
                ('was_offline', models.BooleanField(default=False, help_text='Queued on the device before syncing.')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_events', to='bookings.booking')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_events', to='hiring.engagement')),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_events', to='societies.gate')),
                ('overridden_by', models.ForeignKey(blank=True, help_text='The guard who resolved a below-threshold face match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overrides', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, help_text="The guard. Null for a worker's own self check-in.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['worker', '-occurred_at'], name='attendance__worker__83f103_idx'), models.Index(fields=['society', '-occurred_at'], name='attendance__society_df86b7_idx'), models.Index(fields=['decision', '-occurred_at'], name='attendance__decisio_3dd488_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegisterScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='attendance/registers/%Y/%m/')),
                ('for_date', models.DateField(db_index=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('transcribed', models.BooleanField(default=False)),
                ('transcribed_at', models.DateTimeField(blank=True, null=True)),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_scans', to='societies.gate')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
                ('transcribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcribed_registers', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-for_date', '-created_at'],
                'indexes': [models.Index(fields=['society', '-for_date'], name='attendance__society_0de9ba_idx')],
            },
        ),
    ]
