# Generated by Django 5.2.16 on 2026-08-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceevent',
            name='method',
            field=models.CharField(choices=[('qr', 'QR code scanned'), ('face', 'Face verified'), ('manual', 'Logged manually by the guard'), ('self_checkin', 'Worker checked in from the app'), ('resident_scan', "Resident scanned the worker's card"), ('register', 'Transcribed from the paper register')], max_length=20),
        ),
    ]
