# Generated by Django 5.2.16 on 2026-08-13 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendanceevent_method'),
        ('hiring', '0003_engagement_hourly_rate_engagement_rate_basis_and_more'),
        ('societies', '0004_societybillingconfig'),
        ('workers', '0005_backfill_platform_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField(db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('self', "Worker's own phone, geofenced"), ('resident_scan', 'Resident scanned her card'), ('resident_confirm', 'Resident approved a prompt'), ('derived', 'Derived from gate events'), ('manual', 'Entered by an administrator')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'She is working now'), ('closed', 'Finished normally'), ('auto_closed', 'Closed automatically, needs a look'), ('cancelled_at_door', 'Cancelled after she arrived'), ('no_show', 'Did not attend')], db_default='open', db_index=True, default='open', max_length=20)),
                ('approved_ot_minutes', models.PositiveSmallIntegerField(db_default=0, default=0)),
                ('needs_review', models.BooleanField(db_default=False, db_index=True, default=False)),
                ('review_note', models.CharField(blank=True, db_default='', max_length=300)),
                ('priced_at', models.DateTimeField(blank=True, null=True)),
                ('billable_minutes', models.PositiveIntegerField(db_default=0, default=0)),
                ('overtime_minutes', models.PositiveIntegerField(db_default=0, default=0)),
                ('unbilled_extra_minutes', models.PositiveIntegerField(db_default=0, default=0)),
                ('time_paise', models.PositiveIntegerField(db_default=0, default=0)),
                ('overtime_paise', models.PositiveIntegerField(db_default=0, default=0)),
                ('visit_fee_paise', models.PositiveIntegerField(db_default=0, default=0)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_work_sessions', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to='hiring.engagement')),
                ('entry_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_sessions', to='attendance.attendanceevent')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_work_sessions', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to='workers.workerprofile')),
            ],
            options={
                'verbose_name': 'work session',
                'verbose_name_plural': 'work sessions',
                'ordering': ['-visit_date', '-started_at'],
                'indexes': [models.Index(fields=['worker', '-visit_date'], name='attendance__worker__08bb97_idx'), models.Index(fields=['society', '-visit_date'], name='attendance__society_a744ee_idx'), models.Index(fields=['status', '-visit_date'], name='attendance__status_1ad38e_idx')],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'visit_date'), name='one_session_per_engagement_day')],
            },
        ),
    ]
