# Generated by Django 5.2.16 on 2026-07-30 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('societies', '0002_society_allow_resident_self_checkin_and_more'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('icon', models.CharField(blank=True, help_text='Material icon name; the UI is icon-led for low-literacy users.', max_length=40)),
                ('expected_duration_minutes', models.PositiveSmallIntegerField(default=120, help_text='Prefills the booking form and sets the default quote.')),
                ('price_min', models.PositiveIntegerField(help_text='Indicative floor, INR.')),
                ('price_max', models.PositiveIntegerField(help_text='Indicative ceiling, INR.')),
                ('bypasses_notice_period', models.BooleanField(default=False, help_text="Exempts this category from the society's minimum booking notice. Set for emergency assistance: a notice window that blocks an emergency defeats the purpose of the category.")),
                ('is_active', models.BooleanField(default=True)),
                ('service_type', models.ForeignKey(blank=True, help_text='Which kind of worker is qualified for this job. Module 5.3 narrows the candidate pool with it. Null means any approved worker may be booked, which is the right default for a category no existing service type cleanly covers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_categories', to='workers.servicetype')),
            ],
            options={
                'verbose_name_plural': 'service categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DayAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('is_available', models.BooleanField(default=True, help_text='True opts into this date; False blocks it out.')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_availability', to='workers.workerprofile')),
            ],
            options={
                'verbose_name_plural': 'day availability',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'is_available'], name='bookings_da_date_4cd0b6_idx')],
                'constraints': [models.UniqueConstraint(fields=('worker', 'date'), name='one_availability_row_per_worker_day')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('expected_duration_minutes', models.PositiveSmallIntegerField(default=120)),
                ('quoted_price', models.PositiveIntegerField(help_text='Agreed price for the job in INR, fixed when the booking is made.')),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', "Awaiting the worker's confirmation"), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('declined', 'Declined by the worker'), ('cancelled', 'Cancelled'), ('expired', 'Not confirmed before the start time')], db_index=True, default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('response_note', models.TextField(blank=True, max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('resident', 'Resident'), ('worker', 'Worker'), ('admin', 'Society administrator')], max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, max_length=500)),
                ('cancellation_fee', models.PositiveIntegerField(default=0, help_text='Charged at cancellation, in INR. Stored rather than recomputed: the policy may change later, and what was charged at the time must not silently change with it. Module 8 settles this amount.')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='societies.resident')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='workers.workerprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.servicecategory')),
            ],
            options={
                'ordering': ['-scheduled_date', '-start_time'],
                'indexes': [models.Index(fields=['worker', 'scheduled_date', 'status'], name='bookings_bo_worker__390d50_idx'), models.Index(fields=['resident', '-scheduled_date'], name='bookings_bo_residen_efc71e_idx'), models.Index(fields=['status', 'scheduled_date'], name='bookings_bo_status_b26418_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('worker', 'scheduled_date', 'start_time'), name='one_live_booking_per_worker_slot')],
            },
        ),
    ]
