# Generated by Django 5.2.16 on 2026-08-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seed_service_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='bypasses_notice_period',
            field=models.BooleanField(default=False, help_text="Exempts this category from the society's minimum booking notice, and from requiring workers to have pre-marked the date as one they can work (see bookings.services.candidate_workers). Set for emergency assistance: nobody pre-declares availability for an emergency that has not happened yet, so a category meant to be bookable at short notice needs both exemptions to actually work."),
        ),
    ]
