# Generated by Django 5.2.16 on 2026-08-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_servicecategory_bypasses_notice_period'),
        ('workers', '0003_workerprofile_police_verification_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='broadcast_at',
            field=models.DateTimeField(blank=True, help_text='When the request was released to workers.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='emergency_surcharge_paise',
            field=models.PositiveIntegerField(default=0, help_text="Module 5.5 — the platform's emergency fee, in paise, fixed when the request was raised. Zero on every ordinary booking."),
        ),
        migrations.AddField(
            model_name='booking',
            name='offer_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When an unclaimed broadcast gives up. Indexed because the sweep that closes lapsed requests runs on ordinary read paths.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Awaiting the emergency surcharge'), ('broadcast', 'Offered to available workers'), ('pending', "Awaiting the worker's confirmation"), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('declined', 'Declined by the worker'), ('cancelled', 'Cancelled'), ('expired', 'Not confirmed before the start time'), ('unfulfilled', 'Nobody accepted in time')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='workers.workerprofile'),
        ),
        migrations.CreateModel(
            name='BookingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('offered', 'Waiting for an answer'), ('accepted', 'Accepted — this worker got the job'), ('declined', 'Declined'), ('lost', 'Another worker accepted first'), ('expired', 'The request lapsed unanswered')], db_index=True, default='offered', max_length=20)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='bookings.booking')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_offers', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['rank', 'created_at'],
                'indexes': [models.Index(fields=['worker', 'state'], name='bookings_bo_worker__a4cf84_idx'), models.Index(fields=['booking', 'state'], name='bookings_bo_booking_99d672_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking', 'worker'), name='one_offer_per_worker_per_booking'), models.UniqueConstraint(condition=models.Q(('state', 'accepted')), fields=('booking',), name='one_accepted_offer_per_booking')],
            },
        ),
    ]
