# Generated by Django 5.2.16 on 2026-07-31 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('societies', '0003_resident_average_rating_resident_rating_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('account', 'Account and verification'), ('hire', 'Hire requests'), ('booking', 'One-day bookings'), ('schedule', 'Upcoming visits'), ('attendance', 'Attendance'), ('gate_entry', 'Gate entry alerts'), ('urgent_leave', 'Urgent leave and replacements'), ('payment', 'Payments'), ('rating', 'Ratings and reviews'), ('complaint', 'Complaints')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=400)),
                ('data', models.JSONField(blank=True, default=dict, help_text="Where tapping it should go — e.g. {'route': '/gate/log'}. Kept as data rather than a URL so the app decides its own navigation.")),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('push_state', models.CharField(choices=[('pending', 'Not attempted yet'), ('sent', 'Accepted by the provider'), ('failed', 'The provider refused or could not be reached'), ('skipped', 'Not attempted — muted, unavailable, or no address')], default='pending', max_length=20)),
                ('sms_state', models.CharField(choices=[('pending', 'Not attempted yet'), ('sent', 'Accepted by the provider'), ('failed', 'The provider refused or could not be reached'), ('skipped', 'Not attempted — muted, unavailable, or no address')], default='pending', max_length=20)),
                ('delivery_note', models.CharField(blank=True, help_text='Why a channel failed or was skipped. For operators, not users.', max_length=300)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx'), models.Index(fields=['push_state', 'sms_state'], name='notificatio_push_st_802c79_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('account', 'Account and verification'), ('hire', 'Hire requests'), ('booking', 'One-day bookings'), ('schedule', 'Upcoming visits'), ('attendance', 'Attendance'), ('gate_entry', 'Gate entry alerts'), ('urgent_leave', 'Urgent leave and replacements'), ('payment', 'Payments'), ('rating', 'Ratings and reviews'), ('complaint', 'Complaints')], max_length=30)),
                ('muted', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
                'constraints': [models.UniqueConstraint(fields=('user', 'category'), name='one_preference_per_user_category')],
            },
        ),
    ]
