# Generated by Django 5.2.16 on 2026-07-31 09:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_seed_service_categories'),
        ('hiring', '0001_initial'),
        ('societies', '0003_resident_average_rating_resident_rating_count_and_more'),
        ('workers', '0002_workerprofile_rating_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('resident_to_worker', 'Resident rating a worker'), ('worker_to_resident', 'Worker rating a resident')], db_index=True, max_length=30)),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, help_text='The raw text as written. Never overwritten by analysis.', max_length=1000)),
                ('is_flagged', models.BooleanField(db_index=True, default=False, help_text='Matched a suspicious pattern. Escalated, never auto-deleted.')),
                ('is_withheld', models.BooleanField(default=False, help_text="Excluded from scoring pending an administrator's review.")),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='bookings.booking')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='hiring.engagement')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='societies.resident')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('burst', 'Many ratings from one person in a short window'), ('uniform', 'Suspiciously uniform ratings for one subject'), ('duplicate_text', 'Near-identical review text'), ('self_interest', 'Rater appears connected to the subject')], max_length=30)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('open', 'Awaiting review'), ('upheld', 'Confirmed — the rating stays withheld'), ('dismissed', 'Cleared — the rating counts again')], db_index=True, default='open', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=300)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='ratings.rating')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_review_flags', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('unknown', 'Could not be determined')], default='unknown', max_length=20)),
                ('polarity', models.FloatField(default=0.0, help_text='-1 (negative) to +1 (positive).')),
                ('confidence', models.FloatField(default=0.0)),
                ('themes', models.JSONField(blank=True, default=dict, help_text='Per-theme verdicts — punctuality, hygiene, behaviour, quality — so a resident reading a profile sees more than one average.')),
                ('detected_language', models.CharField(blank=True, help_text='Reviews arrive in Hindi, Hinglish and English, often mixed.', max_length=20)),
                ('engine', models.CharField(blank=True, max_length=30)),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='ratings.rating')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(choices=[('worker', 'Worker'), ('resident', 'Resident')], max_length=20)),
                ('previous_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('new_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('components', models.JSONField(blank=True, default=list, help_text='Per-component weight, value and contribution, frozen at the time.')),
                ('trigger', models.CharField(blank=True, help_text='What caused the recomputation — a rating, a job, a batch run.', max_length=60)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trust_logs', to='societies.resident')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trust_logs', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['worker', 'direction', '-created_at'], name='ratings_rat_worker__08697e_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['resident', 'direction', '-created_at'], name='ratings_rat_residen_cb7044_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rater', '-created_at'], name='ratings_rat_rater_i_59a8e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('engagement__isnull', False)), fields=('engagement', 'direction'), name='one_rating_per_engagement_per_direction'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False)), fields=('booking', 'direction'), name='one_rating_per_booking_per_direction'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', True), ('engagement__isnull', False)), models.Q(('booking__isnull', False), ('engagement__isnull', True)), _connector='OR'), name='rating_targets_exactly_one_job'),
        ),
        migrations.AddIndex(
            model_name='reviewflag',
            index=models.Index(fields=['society', 'status', '-created_at'], name='ratings_rev_society_4cf8d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewflag',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('rating', 'reason'), name='one_open_flag_per_rating_reason'),
        ),
        migrations.AddIndex(
            model_name='reviewsentiment',
            index=models.Index(fields=['label', '-created_at'], name='ratings_rev_label_985742_idx'),
        ),
        migrations.AddIndex(
            model_name='trustscorelog',
            index=models.Index(fields=['worker', '-created_at'], name='ratings_tru_worker__263e90_idx'),
        ),
        migrations.AddIndex(
            model_name='trustscorelog',
            index=models.Index(fields=['resident', '-created_at'], name='ratings_tru_residen_1390d7_idx'),
        ),
    ]
