# Generated by Django 5.2.16 on 2026-07-31 14:35

import apps.administration.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('societies', '0003_resident_average_rating_resident_rating_count_and_more'),
        ('workers', '0002_workerprofile_rating_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentDirectory',
            fields=[
            ],
            options={
                'verbose_name': 'resident (directory)',
                'verbose_name_plural': 'resident directory',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('societies.resident',),
        ),
        migrations.CreateModel(
            name='WorkerDirectory',
            fields=[
            ],
            options={
                'verbose_name': 'worker (directory)',
                'verbose_name_plural': 'worker directory',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('workers.workerprofile',),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('category', models.CharField(choices=[('late_arrival', 'Late or missed visit'), ('behaviour', 'Behaviour or conduct'), ('payment', 'Payment'), ('quality', 'Quality of work'), ('safety', 'Safety or security'), ('other', 'Something else')], db_index=True, max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=2000)),
                ('photo', models.ImageField(blank=True, help_text='Optional evidence — damage, a paper record, a gate log.', upload_to=apps.administration.models.complaint_photo_path)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal')], db_index=True, default='normal', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'Being looked into'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by the person who raised it')], db_index=True, default='open', max_length=20)),
                ('sla_due_at', models.DateTimeField(blank=True, db_index=True, help_text='Set once at creation from the priority. Never recomputed.', null=True)),
                ('escalated_at', models.DateTimeField(blank=True, help_text='When the deadline passed and the sweep raised the alarm.', null=True)),
                ('first_response_at', models.DateTimeField(blank=True, help_text='When an administrator first acted. The number that matters.', null=True)),
                ('resolution', models.TextField(blank=True, max_length=2000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('against_resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_against', to='societies.resident')),
                ('against_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_against', to='workers.workerprofile')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_assigned', to=settings.AUTH_USER_MODEL)),
                ('payment_dispute', models.OneToOneField(blank=True, help_text='Set when this complaint was opened from a payment dispute. Module 8.6 deliberately kept its own record thin and routed the handling here rather than building a second workflow.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='payments.paymentdispute')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_resolved', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(max_length=2000)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('is_internal', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_updates', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='administration.complaint')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnmetDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('no_match', 'No worker was free for the requested slot'), ('hire_lapsed', 'A hire request expired unanswered'), ('urgent_replacement', 'An urgent replacement could not be found')], db_index=True, max_length=30)),
                ('service_label', models.CharField(blank=True, help_text='What was asked for, as the person asking would name it.', max_length=120)),
                ('requested_date', models.DateField(blank=True, db_index=True, null=True)),
                ('requested_time', models.TimeField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmet_demand', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
            ],
            options={
                'verbose_name': 'unmet demand',
                'verbose_name_plural': 'unmet demand',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['society', 'status', '-created_at'], name='administrat_society_3bfaa9_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['society', 'priority', 'sla_due_at'], name='administrat_society_efc8ae_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['against_worker', '-created_at'], name='administrat_against_eeb21a_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['raised_by', '-created_at'], name='administrat_raised__f7caf7_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintupdate',
            index=models.Index(fields=['complaint', 'created_at'], name='administrat_complai_12e9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='unmetdemand',
            index=models.Index(fields=['society', 'kind', '-created_at'], name='administrat_society_322a82_idx'),
        ),
        migrations.AddIndex(
            model_name='unmetdemand',
            index=models.Index(fields=['society', 'service_label'], name='administrat_society_8a8c48_idx'),
        ),
    ]
