# Generated by Django 5.2.16 on 2026-08-13 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('societies', '0004_societybillingconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('attendance', 'Attendance'), ('payments', 'Payments'), ('complaints', 'Complaints')], max_length=20)),
                ('scope', models.CharField(choices=[('all', 'Every society'), ('tier', 'Every society on a subscription tier'), ('selected', 'A chosen list of societies')], default='all', max_length=20)),
                ('tier', models.CharField(blank=True, db_default='', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('formats', models.JSONField(default=list)),
                ('include_pii', models.BooleanField(db_default=False, default=False)),
                ('reason', models.CharField(blank=True, db_default='', max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Queued, waiting for a sweep'), ('running', 'Being built'), ('ready', 'Finished'), ('partial', 'Finished with some societies missing'), ('failed', 'Could not be built')], db_default='pending', db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(db_default=0, default=0)),
                ('last_error', models.CharField(blank=True, db_default='', max_length=300)),
                ('csv_file', models.FileField(blank=True, upload_to='reports/%Y/%m/')),
                ('pdf_file', models.FileField(blank=True, upload_to='reports/%Y/%m/')),
                ('row_count', models.PositiveIntegerField(db_default=0, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_jobs', to=settings.AUTH_USER_MODEL)),
                ('societies', models.ManyToManyField(blank=True, related_name='report_jobs', to='societies.society')),
            ],
            options={
                'verbose_name': 'report job',
                'verbose_name_plural': 'report jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportJobSociety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Queued, waiting for a sweep'), ('running', 'Being built'), ('ready', 'Finished'), ('partial', 'Finished with some societies missing'), ('failed', 'Could not be built')], db_default='pending', default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(db_default=0, default=0)),
                ('row_count', models.PositiveIntegerField(db_default=0, default=0)),
                ('last_error', models.CharField(blank=True, db_default='', max_length=300)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_jobs', to='administration.reportjob')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_job_slices', to='societies.society')),
            ],
            options={
                'verbose_name': 'report job society',
                'verbose_name_plural': 'report job societies',
                'ordering': ['society__name'],
            },
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['status', '-created_at'], name='administrat_status_a4c041_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportjobsociety',
            constraint=models.UniqueConstraint(fields=('job', 'society'), name='one_slice_per_society_per_job'),
        ),
    ]
