# Generated by Django 5.2.16 on 2026-07-30 18:26

import apps.workers.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Material icon name; the Flutter UI is icon-led for low-literacy users.', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, help_text='Profile photo. Also the reference image for gate face verification in Module 7, which is why it is required before approval.', upload_to=apps.workers.models.worker_photo_path)),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('languages_spoken', models.CharField(blank=True, help_text='Comma-separated, e.g. Hindi, Marathi', max_length=120)),
                ('expected_monthly_rate', models.PositiveIntegerField(blank=True, help_text='Indicative monthly rate in INR.', null=True)),
                ('is_available', models.BooleanField(default=True, help_text="Worker's own toggle. Hides them from search without deactivating them.")),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_until', models.TimeField(blank=True, null=True)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0, help_text='Computed by Module 9. Zero until enough history accumulates.', max_digits=5)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('completed_engagements', models.PositiveIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_workers', to=settings.AUTH_USER_MODEL)),
                ('service_types', models.ManyToManyField(blank=True, related_name='workers', to='workers.servicetype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trust_score', '-average_rating'],
            },
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_image', models.FileField(upload_to=apps.workers.models.kyc_document_path)),
                ('status', models.CharField(choices=[('pending', 'Awaiting processing'), ('processing', 'OCR in progress'), ('completed', 'OCR completed'), ('failed', 'OCR failed — manual entry required')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('extracted_name', models.CharField(blank=True, max_length=120)),
                ('extracted_dob', models.CharField(blank=True, max_length=20)),
                ('extracted_gender', models.CharField(blank=True, max_length=20)),
                ('aadhaar_last4', models.CharField(blank=True, max_length=4)),
                ('aadhaar_hash', models.CharField(blank=True, db_index=True, help_text='Keyed HMAC of the full number. Global de-duplication key.', max_length=64)),
                ('aadhaar_checksum_valid', models.BooleanField(default=False, help_text='Stage 7 — Verhoeff validation result.')),
                ('extracted_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_minor', models.BooleanField(default=False, help_text='Under 18. Triggers automatic, non-overridable rejection.')),
                ('ocr_engine', models.CharField(blank=True, max_length=30)),
                ('mean_confidence', models.FloatField(default=0.0)),
                ('low_confidence_fields', models.JSONField(blank=True, default=list, help_text='Fields read below the threshold; must be confirmed manually.')),
                ('cross_check', models.JSONField(blank=True, default=dict, help_text='Stage 8 per-field matched/mismatch verdicts.')),
                ('has_mismatch', models.BooleanField(default=False)),
                ('ocr_summary', models.JSONField(blank=True, default=dict, help_text='Full safe pipeline summary, shown in the admin review screen.')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('kyc_aadhaar', 'Identity verification using Aadhaar'), ('face_biometric', 'Face verification at the society gate'), ('data_processing', 'General platform data processing')], max_length=30)),
                ('granted', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('policy_version', models.CharField(default='1.0', help_text='Which privacy policy version the user actually agreed to.', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'granted'], name='workers_con_user_id_88d37d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['is_available', '-trust_score'], name='workers_wor_is_avai_48e249_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['status', '-created_at'], name='workers_kyc_status_2e2354_idx'),
        ),
    ]
