# Generated by Django 5.2.16 on 2026-07-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='How many ratings the average is over. Maintained by Module 9. Module 4.3 needs it to shrink a sparse average toward the prior — one five-star review is not the same evidence as fifty.'),
        ),
    ]
