# Generated by Django 5.2.16 on 2026-08-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workerprofile_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='police_verification_reference',
            field=models.CharField(blank=True, help_text="The verifying agency's reference, so a badge can be audited.", max_length=64),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='police_verified_at',
            field=models.DateField(blank=True, help_text='When the police check was completed. Displayed with the badge.', null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='police_verified_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
