# Generated by Django 5.2.16 on 2026-08-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_workerprofile_police_verification_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='expected_monthly_rate',
            field=models.PositiveIntegerField(blank=True, default=2500, help_text='The platform monthly rate, in INR. Mirrored onto the profile so Module 4 search can sort and filter without a join; the worker does not set it. See apps.core.pricing.', null=True),
        ),
    ]
