# Generated by Django 5.2.16 on 2026-07-30 15:11

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(help_text='Primary login identifier. Indian mobile number.', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian mobile number, e.g. 9876543210.', regex='^(\\+91)?[6-9]\\d{9}$')], verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('role', models.CharField(choices=[('resident', 'Resident'), ('worker', 'Domestic Worker'), ('guard', 'Security Guard'), ('society_admin', 'Society Administrator')], db_index=True, help_text='Determines which endpoints and dashboards this user may access.', max_length=20, verbose_name='role')),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Set by a society administrator. An unapproved user can authenticate but cannot transact: workers stay out of search results and residents cannot hire.', verbose_name='approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'हिन्दी'), ('mr', 'मराठी')], default='en', help_text='Drives Flutter UI language; multilingual support is MVP scope.', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('society', models.ForeignKey(blank=True, help_text='Multi-tenancy anchor. Null only for platform staff and for a society administrator during initial society registration.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='societies.society')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'indexes': [models.Index(fields=['society', 'role', 'is_approved'], name='accounts_us_society_44d163_idx')],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
