# Generated by Django 5.2.16 on 2026-07-30 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=13)),
                ('code_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('registration', 'Phone verification at registration'), ('login', 'Passwordless login'), ('password_reset', 'Password reset')], default='registration', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'purpose', '-created_at'], name='accounts_ot_phone_n_1600d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Stable client-generated identifier for this installation.', max_length=128)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('platform', models.CharField(blank=True, max_length=20)),
                ('refresh_token_jti', models.CharField(blank=True, db_index=True, max_length=64)),
                ('fcm_token', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='accounts_de_user_id_45e55c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='unique_session_per_user_device')],
            },
        ),
    ]
