# Generated by Django 5.2.16 on 2026-08-13 14:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp_purposes_and_role_constraint'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('societies', '0004_societybillingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('reads', models.PositiveIntegerField(default=0)),
                ('writes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'impersonation grant',
                'verbose_name_plural': 'impersonation grants',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(db_index=True, max_length=100)),
                ('action', models.CharField(default='read', max_length=40)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'platform access log',
                'verbose_name_plural': 'platform access logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuperadminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('support', 'Support — read and impersonate'), ('finance', 'Finance — read, refund, settle')], max_length=20)),
                ('may_refund', models.BooleanField(default=False)),
                ('may_settle_manually', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'superadmin profile',
                'verbose_name_plural': 'superadmin profiles',
            },
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='user_role_is_one_of_the_four_roles',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('resident', 'Resident'), ('worker', 'Domestic Worker'), ('guard', 'Security Guard'), ('society_admin', 'Society Administrator'), ('superadmin', 'Platform Operator')], db_index=True, help_text='Determines which endpoints and dashboards this user may access.', max_length=20, verbose_name='role'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['resident', 'worker', 'guard', 'society_admin', 'superadmin'])), name='user_role_is_a_known_role'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'superadmin'), ('society__isnull', True)), models.Q(('role', 'superadmin'), _negated=True), _connector='OR'), name='superadmin_belongs_to_no_society'),
        ),
        migrations.AddField(
            model_name='impersonationgrant',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_grants', to='societies.society'),
        ),
        migrations.AddField(
            model_name='impersonationgrant',
            name='superadmin',
            field=models.ForeignKey(limit_choices_to={'role': 'superadmin'}, on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impersonationgrant',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonated_by_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platformaccesslog',
            name='society',
            field=models.ForeignKey(blank=True, help_text='Null when the read genuinely spanned every society.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_access_logs', to='societies.society'),
        ),
        migrations.AddField(
            model_name='platformaccesslog',
            name='superadmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='superadminprofile',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_superadmin_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='superadminprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'superadmin'}, on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='impersonationgrant',
            index=models.Index(fields=['society', '-started_at'], name='accounts_im_society_831ba1_idx'),
        ),
        migrations.AddConstraint(
            model_name='impersonationgrant',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='impersonation_requires_a_reason'),
        ),
        migrations.AddIndex(
            model_name='platformaccesslog',
            index=models.Index(fields=['society', '-created_at'], name='accounts_pl_society_3be94a_idx'),
        ),
        migrations.AddIndex(
            model_name='platformaccesslog',
            index=models.Index(fields=['superadmin', '-created_at'], name='accounts_pl_superad_0c69a9_idx'),
        ),
    ]
