# Generated by Django 5.2.16 on 2026-07-31 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('societies', '0003_resident_average_rating_resident_rating_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiUsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(db_index=True, max_length=30)),
                ('window', models.CharField(choices=[('minute', 'Per minute'), ('day', 'Per day')], max_length=10)),
                ('bucket', models.CharField(max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['tier', 'window', 'bucket'], name='ai_services_tier_73bda0_idx')],
                'constraints': [models.UniqueConstraint(fields=('tier', 'window', 'bucket'), name='one_counter_per_bucket')],
            },
        ),
        migrations.CreateModel(
            name='AiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.CharField(choices=[('chat', '12.2 Chatbot'), ('review_summary', '12.5 Review summary'), ('sentiment', '12.5 Review sentiment'), ('complaint_classify', '12.5 Complaint classification'), ('recommendation', '12.1 Worker recommendation'), ('ocr', '12.3 Document extraction'), ('face', '12.4 Face verification')], db_index=True, max_length=30)),
                ('outcome', models.CharField(choices=[('ai', 'A provider answered'), ('fallback', 'The rule-based fallback answered'), ('unavailable', 'Nothing could answer')], db_index=True, default='ai', max_length=20)),
                ('tier', models.CharField(blank=True, db_index=True, max_length=30)),
                ('tiers_attempted', models.JSONField(blank=True, default=list)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('prompt_chars', models.PositiveIntegerField(default=0)),
                ('response_chars', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='societies.society')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature', '-created_at'], name='ai_services_feature_70f6ca_idx'), models.Index(fields=['outcome', '-created_at'], name='ai_services_outcome_474006_idx')],
            },
        ),
    ]
