# Generated by Django 5.2.16 on 2026-07-30 18:35

import apps.hiring.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('societies', '0002_society_allow_resident_self_checkin_and_more'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_of_week', models.JSONField(default=list, help_text='Monday=0 … Sunday=6, e.g. [0,1,2,3,4] for weekdays.', validators=[apps.hiring.models.validate_days_of_week])),
                ('start_time', models.TimeField(help_text='Expected arrival time.')),
                ('expected_duration_minutes', models.PositiveSmallIntegerField(default=60, help_text='Used by Module 7 to judge whether a visit was short-served.')),
                ('monthly_rate', models.PositiveIntegerField(help_text='Agreed monthly pay in INR.')),
                ('message', models.TextField(blank=True, help_text='Optional note from the resident.', max_length=500)),
                ('status', models.CharField(choices=[('pending', "Awaiting the worker's response"), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn by the resident'), ('expired', 'Lapsed without a response')], db_index=True, default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True, default=apps.hiring.models.default_response_deadline)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_note', models.TextField(blank=True, help_text="The worker's reason, chiefly when declining.", max_length=500)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests', to='societies.resident')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hire_requests', to='workers.servicetype')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_of_week', models.JSONField(default=list, help_text='Monday=0 … Sunday=6, e.g. [0,1,2,3,4] for weekdays.', validators=[apps.hiring.models.validate_days_of_week])),
                ('start_time', models.TimeField(help_text='Expected arrival time.')),
                ('expected_duration_minutes', models.PositiveSmallIntegerField(default=60, help_text='Used by Module 7 to judge whether a visit was short-served.')),
                ('monthly_rate', models.PositiveIntegerField(help_text='Agreed monthly pay in INR.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('terminated', 'Terminated')], db_index=True, default='active', max_length=20)),
                ('started_on', models.DateField(default=datetime.date.today)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('pause_reason', models.CharField(blank=True, max_length=200)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('resident_ended', 'Ended by the resident'), ('worker_ended', 'Ended by the worker'), ('resident_moved_out', 'Resident moved out'), ('worker_left_society', 'Worker stopped working here'), ('admin_ended', 'Ended by an administrator')], max_length=30)),
                ('end_note', models.TextField(blank=True, max_length=500)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_engagements', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='societies.resident')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='workers.servicetype')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='workers.workerprofile')),
                ('hire_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement', to='hiring.hirerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hirerequest',
            index=models.Index(fields=['worker', 'status', '-created_at'], name='hiring_hire_worker__aa0ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='hirerequest',
            index=models.Index(fields=['status', 'expires_at'], name='hiring_hire_status_abde96_idx'),
        ),
        migrations.AddConstraint(
            model_name='hirerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('resident', 'worker', 'service_type'), name='one_pending_hire_request_per_pair'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['worker', 'status'], name='hiring_enga_worker__abe7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['resident', 'status'], name='hiring_enga_residen_8658c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'paused'])), fields=('resident', 'worker', 'service_type'), name='one_live_engagement_per_pair'),
        ),
    ]
