# Generated by Django 5.2.16 on 2026-08-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_engagement_last_working_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='hourly_rate',
            field=models.PositiveIntegerField(db_default=0, default=0, help_text='Agreed hourly pay in INR. Zero on monthly terms.'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='rate_basis',
            field=models.CharField(choices=[('monthly', 'A fixed monthly rate'), ('hourly', 'A visit fee plus an hourly rate')], db_default='monthly', default='monthly', help_text='Monthly unless both parties opted into hourly.', max_length=10),
        ),
        migrations.AddField(
            model_name='engagement',
            name='visit_fee',
            field=models.PositiveIntegerField(db_default=0, default=0, help_text='Flat fee per visit in INR, covering travel and the committed slot. Zero on monthly terms.'),
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='hourly_rate',
            field=models.PositiveIntegerField(db_default=0, default=0, help_text='Agreed hourly pay in INR. Zero on monthly terms.'),
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='rate_basis',
            field=models.CharField(choices=[('monthly', 'A fixed monthly rate'), ('hourly', 'A visit fee plus an hourly rate')], db_default='monthly', default='monthly', help_text='Monthly unless both parties opted into hourly.', max_length=10),
        ),
        migrations.AddField(
            model_name='hirerequest',
            name='visit_fee',
            field=models.PositiveIntegerField(db_default=0, default=0, help_text='Flat fee per visit in INR, covering travel and the committed slot. Zero on monthly terms.'),
        ),
    ]
