# Generated by Django 5.2.16 on 2026-07-31 05:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_seed_service_categories'),
        ('hiring', '0001_initial'),
        ('societies', '0002_society_allow_resident_self_checkin_and_more'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('engagement_salary', 'Monthly salary for a recurring hire'), ('booking', 'One-day booking'), ('tip', 'Tip'), ('refund', 'Refund'), ('replacement', "Replacement worker's share")], db_index=True, max_length=30)),
                ('amount_paise', models.PositiveIntegerField(help_text='Base amount, in paise.')),
                ('tip_paise', models.PositiveIntegerField(default=0, help_text='Module 8.4 — charged in the same Razorpay transaction, not separately, so the resident authorises one amount.')),
                ('refunded_paise', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('created', 'Order created, not yet attempted'), ('pending', 'Awaiting confirmation from Razorpay'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled before payment')], db_index=True, default='created', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('razorpay_signature', models.CharField(blank=True, max_length=128)),
                ('receipt_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('period_start', models.DateField(blank=True, help_text='For a monthly salary payment.', null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='hiring.engagement')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='societies.resident')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('not_paid', 'Payment never arrived'), ('wrong_amount', 'The amount is wrong'), ('hours_disputed', 'The hours worked are disputed'), ('not_provided', 'The service was not provided'), ('other', 'Something else')], max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'With the administrator'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='open', max_length=20)),
                ('resolution', models.TextField(blank=True, max_length=1000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='payments.payment')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_payment_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_payment_disputes', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplacementSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replacement_share_percent', models.PositiveSmallIntegerField(default=100, help_text="Share of the day's pay going to the replacement worker.")),
                ('note', models.CharField(blank=True, max_length=300)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_split', to='hiring.engagement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_replacement_splits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(db_index=True, help_text="Razorpay's x-razorpay-event-id header.", max_length=128, unique=True)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('process_error', models.CharField(blank=True, max_length=300)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['worker', '-paid_at'], name='payments_pa_worker__1992cf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['resident', '-created_at'], name='payments_pa_residen_2fd832_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdispute',
            index=models.Index(fields=['society', 'status', '-created_at'], name='payments_pa_society_4cc486_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentdispute',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'under_review'])), fields=('payment', 'raised_by'), name='one_open_dispute_per_payment_per_person'),
        ),
        migrations.AddConstraint(
            model_name='replacementsplit',
            constraint=models.CheckConstraint(condition=models.Q(('replacement_share_percent__lte', 100)), name='replacement_share_at_most_100'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_type', '-created_at'], name='payments_we_event_t_8f0131_idx'),
        ),
    ]
