# Generated by Django 5.2.16 on 2026-08-08 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('societies', '0003_resident_average_rating_resident_rating_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='platform_fee_paise',
            field=models.PositiveIntegerField(default=0, help_text='Platform fee charged on top of the amount, in paise.'),
        ),
        migrations.CreateModel(
            name='SocietySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('plus', 'Plus')], db_index=True, default='free', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('society', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='societies.society')),
            ],
            options={
                'verbose_name': 'society subscription',
            },
        ),
    ]
