# Generated by Django 5.2.16 on 2026-08-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_platform_fee_paise_societysubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
