# Generated by Django 5.2.16 on 2026-08-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_due_at'),
        ('workers', '0003_workerprofile_police_verification_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('engagement_salary', 'Monthly salary for a recurring hire'), ('booking', 'One-day booking'), ('tip', 'Tip'), ('refund', 'Refund'), ('replacement', "Replacement worker's share"), ('emergency_surcharge', 'Emergency booking fee')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='workers.workerprofile'),
        ),
    ]
