# Generated by Django 5.2.16 on 2026-08-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_kind_alter_payment_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('engagement_salary', 'Monthly salary for a recurring hire'), ('booking', 'One-day booking'), ('tip', 'Tip'), ('refund', 'Refund'), ('replacement', "Replacement worker's share"), ('emergency_surcharge', 'Emergency booking fee'), ('notice_settlement', 'Final settlement on notice')], db_index=True, max_length=30),
        ),
    ]
