# Generated by Django 5.2.16 on 2026-08-09 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='settled_via',
            field=models.CharField(blank=True, choices=[('checkout', 'Signed Razorpay checkout response'), ('webhook', 'Razorpay webhook'), ('upi_manual', 'UPI transfer, confirmed against a statement')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='UpiSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utr', models.CharField(db_index=True, help_text="The bank's UTR for this transfer. One UTR settles one payment.", max_length=40, unique=True)),
                ('amount_paise', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('confirmed_by', models.ForeignKey(help_text='Who took responsibility for this confirmation.', on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_upi_settlements', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upi_settlement', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['confirmed_by', '-created_at'], name='payments_up_confirm_c22af5_idx')],
            },
        ),
    ]
