# Generated by Django 5.2.16 on 2026-08-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_settled_via_upisettlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='qr_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_qr_code_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_qr_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
