# Generated by Django 5.2.16 on 2026-08-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_qr_expires_at_payment_razorpay_qr_code_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='razorpay_qr_code_id',
            field=models.CharField(blank=True, db_default='', db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_qr_image_url',
            field=models.URLField(blank=True, db_default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='settled_via',
            field=models.CharField(blank=True, choices=[('checkout', 'Signed Razorpay checkout response'), ('webhook', 'Razorpay webhook'), ('upi_manual', 'UPI transfer, confirmed against a statement')], db_default='', db_index=True, max_length=20),
        ),
    ]
