# Generated by Django 5.2.16 on 2026-08-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payment_razorpay_qr_code_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_link_id',
            field=models.CharField(blank=True, db_default='', db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_link_url',
            field=models.URLField(blank=True, db_default='', max_length=500),
        ),
    ]
