# Generated by Django 5.2.16 on 2026-08-13 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_worksession'),
        ('hiring', '0003_engagement_hourly_rate_engagement_rate_basis_and_more'),
        ('payments', '0009_payment_razorpay_payment_link_id_and_more'),
        ('societies', '0004_societybillingconfig'),
        ('workers', '0005_backfill_platform_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Building through the period'), ('review', 'Open for questions'), ('issued', 'Issued and payable'), ('settled', 'Paid'), ('void', 'Cancelled before issue')], db_default='draft', db_index=True, default='draft', max_length=20)),
                ('review_closes_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('time_paise', models.PositiveIntegerField(db_default=0, default=0)),
                ('overtime_paise', models.PositiveIntegerField(db_default=0, default=0)),
                ('visit_fee_paise', models.PositiveIntegerField(db_default=0, default=0)),
                ('adjustment_paise', models.IntegerField(db_default=0, default=0)),
                ('held_paise', models.PositiveIntegerField(db_default=0, default=0)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='hiring.engagement')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='payments.payment')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='societies.resident')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='workers.workerprofile')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('not_paid', 'Payment never arrived'), ('wrong_amount', 'The amount is wrong'), ('hours_disputed', 'The hours worked are disputed'), ('not_provided', 'The service was not provided'), ('other', 'Something else')], max_length=30)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('stage', models.CharField(choices=[('evidence', 'Both parties shown the record'), ('bilateral', 'Waiting for one side to accept the other'), ('admin', 'With the society administrator'), ('resolved', 'Settled'), ('withdrawn', 'Withdrawn by whoever raised it')], db_default='evidence', db_index=True, default='evidence', max_length=20)),
                ('escalates_at', models.DateTimeField(blank=True, help_text='When this reaches the society administrator if unresolved.', null=True)),
                ('resolution', models.TextField(blank=True, max_length=1000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('adjustment_paise', models.IntegerField(db_default=0, default=0)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='payments.invoice')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_session_queries', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_session_queries', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='attendance.worksession')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
            ],
            options={
                'verbose_name': 'session query',
                'verbose_name_plural': 'session queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('time', 'Time worked'), ('overtime', 'Approved extra time'), ('visit_fee', 'Visit fee'), ('adjustment', 'Adjustment from an earlier period')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('minutes', models.PositiveIntegerField(db_default=0, default=0)),
                ('amount_paise', models.IntegerField()),
                ('is_held', models.BooleanField(db_default=False, default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payments.invoice')),
                ('session', models.ForeignKey(blank=True, help_text='Null on an adjustment carried from an earlier period.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='attendance.worksession')),
                ('query', models.ForeignKey(blank=True, help_text='The query this adjustment answers, when it answers one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_lines', to='payments.sessionquery')),
            ],
            options={
                'verbose_name': 'invoice line',
                'verbose_name_plural': 'invoice lines',
                'ordering': ['invoice', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WageFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('min_hourly_paise', models.PositiveIntegerField(help_text='Statutory minimum per hour, in paise.')),
                ('effective_from', models.DateField(db_index=True)),
                ('source_note', models.CharField(blank=True, help_text='Which notification or order this figure came from.', max_length=300)),
            ],
            options={
                'verbose_name': 'wage floor',
                'verbose_name_plural': 'wage floors',
                'ordering': ['state', '-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('state', 'effective_from'), name='one_wage_floor_per_state_per_date')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['society', '-period_end'], name='payments_in_society_1a1322_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', '-period_end'], name='payments_in_status_aa67b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('engagement', 'period_start', 'period_end'), name='one_invoice_per_engagement_period'),
        ),
        migrations.AddIndex(
            model_name='sessionquery',
            index=models.Index(fields=['society', 'stage', '-created_at'], name='payments_se_society_6fefa2_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionquery',
            constraint=models.UniqueConstraint(condition=models.Q(('stage__in', ['evidence', 'bilateral', 'admin'])), fields=('session', 'raised_by'), name='one_open_query_per_session_per_person'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice', 'kind'], name='payments_in_invoice_04c0bd_idx'),
        ),
    ]
