# Generated by Django 5.2.16 on 2026-07-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(blank=True, help_text='Society registration / RWA number, where one exists.', max_length=100)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(db_index=True, max_length=6)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_towers', models.PositiveSmallIntegerField(default=1)),
                ('total_flats', models.PositiveIntegerField(default=0)),
                ('gate_count', models.PositiveSmallIntegerField(default=1, help_text='Number of staffed gates; each guard is assigned to one.')),
                ('booking_notice_hours', models.PositiveSmallIntegerField(default=12, help_text='Minimum notice required for a one-day booking (Module 5).')),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'societies',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'pincode'), name='unique_society_name_per_pincode')],
            },
        ),
    ]
