# Generated by Django 5.2.16 on 2026-07-30 16:38

import apps.societies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='allow_resident_self_checkin',
            field=models.BooleanField(default=True, help_text='Permits the GPS-geofence attendance fallback when no guard is on duty (Module 13.3, secondary attendance tier).'),
        ),
        migrations.AddField(
            model_name='society',
            name='guard_shift_hours',
            field=models.PositiveSmallIntegerField(default=8, help_text='Length of a guard shift, used by Module 7 rostering.'),
        ),
        migrations.AddField(
            model_name='society',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='society',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='total_flats',
            field=models.PositiveIntegerField(default=0, help_text='Declared flat count, used to sanity-check the mapping.'),
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. "A", "Tower 1", "West Wing"', max_length=50)),
                ('floors', models.PositiveSmallIntegerField(default=1)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towers', to='societies.society')),
            ],
            options={
                'ordering': ['society', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text='e.g. "301", "B-12"', max_length=20)),
                ('floor', models.PositiveSmallIntegerField(default=0)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='societies.tower')),
            ],
            options={
                'ordering': ['tower', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. "Main Gate", "Service Gate"', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='societies.society')),
            ],
            options={
                'ordering': ['society', 'name'],
                'constraints': [models.UniqueConstraint(fields=('society', 'name'), name='unique_gate_name_per_society')],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant'), ('family_member', 'Family member')], default='owner', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text="The flat's primary account holder. Only the primary may create or edit hires and schedules, which prevents two people in one household issuing conflicting bookings.")),
                ('proof_document', models.FileField(blank=True, help_text='Rent agreement, sale deed, utility bill, or similar.', upload_to=apps.societies.models.resident_proof_upload_path)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='societies.flat')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_residents', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['flat', 'is_primary'], name='societies_r_flat_id_6c6b23_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('flat',), name='one_primary_resident_per_flat')],
            },
        ),
        migrations.AddConstraint(
            model_name='tower',
            constraint=models.UniqueConstraint(fields=('society', 'name'), name='unique_tower_name_per_society'),
        ),
        migrations.AddIndex(
            model_name='flat',
            index=models.Index(fields=['tower', 'number'], name='societies_f_tower_i_1f4f76_idx'),
        ),
        migrations.AddConstraint(
            model_name='flat',
            constraint=models.UniqueConstraint(fields=('tower', 'number'), name='unique_flat_number_per_tower'),
        ),
    ]
