# Generated by Django 5.2.16 on 2026-07-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0002_society_allow_resident_self_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='resident',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resident',
            name='trust_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0–100, computed by Module 9. Zero until there is history.', max_digits=5),
        ),
    ]
