# Generated by Django 5.2.16 on 2026-08-13 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0003_resident_average_rating_resident_rating_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyBillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_overhead_minutes', models.PositiveSmallIntegerField(db_default=30, default=30, help_text='Fixed overhead per visit, used to calibrate the visit fee.')),
                ('visit_fee_policy', models.CharField(choices=[('per_engagement', 'Every visit charges the full fee'), ('first_of_day', "Only the day's first visit charges the fee"), ('shared_pro_rata', "The day's visits share one fee")], db_default='per_engagement', default='per_engagement', max_length=20)),
                ('round_minutes', models.PositiveSmallIntegerField(db_default=15, default=15)),
                ('round_up_in_workers_favour', models.BooleanField(db_default=False, default=False)),
                ('ot_multiplier_bp', models.PositiveIntegerField(db_default=10000, default=10000)),
                ('autoclose_after_minutes', models.PositiveSmallIntegerField(db_default=90, default=90)),
                ('free_cancellation_hours', models.PositiveSmallIntegerField(db_default=12, default=12)),
                ('review_window_hours', models.PositiveSmallIntegerField(db_default=48, default=48)),
                ('society', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_config', to='societies.society')),
            ],
            options={
                'verbose_name': 'society billing config',
                'verbose_name_plural': 'society billing configs',
            },
        ),
    ]
