# Generated by Django 5.2.16 on 2026-07-31 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_seed_service_categories'),
        ('hiring', '0001_initial'),
        ('societies', '0002_society_allow_resident_self_checkin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_arrival', models.TimeField(blank=True, help_text="Defaults to the engagement's own start time.", null=True)),
                ('arrival_grace_minutes', models.PositiveSmallIntegerField(default=15, help_text='How late an arrival may be before it counts as late.')),
                ('expected_departure', models.TimeField(blank=True, help_text="Defaults to arrival plus the engagement's expected duration.", null=True)),
                ('departure_grace_minutes', models.PositiveSmallIntegerField(default=15, help_text='How early a departure may be before it counts as short-served.')),
                ('task_notes', models.TextField(blank=True, help_text='What the resident expects done, shown to the worker each visit.', max_length=1000)),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('reminder_lead_minutes', models.PositiveSmallIntegerField(default=60, help_text='How far ahead of the expected arrival to remind.')),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_timing', to='hiring.engagement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_task_timings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'task timing',
                'verbose_name_plural': 'task timings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('upcoming_engagement', 'Recurring visit due'), ('upcoming_booking', 'One-day booking due'), ('booking_unconfirmed', 'Booking still unconfirmed')], max_length=30)),
                ('event_at', models.DateTimeField(db_index=True)),
                ('send_after', models.DateTimeField(db_index=True)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('scheduled', 'Waiting to be sent'), ('sent', 'Sent'), ('cancelled', 'Cancelled before sending'), ('failed', 'Delivery failed')], db_index=True, default='scheduled', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='bookings.booking')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='hiring.engagement')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
            ],
            options={
                'ordering': ['send_after'],
                'indexes': [models.Index(fields=['status', 'send_after'], name='scheduling__status_cd1c2d_idx'), models.Index(fields=['recipient', 'status'], name='scheduling__recipie_08d86c_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'kind', 'event_at'), name='one_reminder_per_recipient_event')],
            },
        ),
    ]
