# Generated by Django 5.2.16 on 2026-08-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('societies', '0003_resident_average_rating_resident_rating_count_and_more'),
        ('workers', '0002_workerprofile_rating_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_date', models.DateField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('waived', 'Resident needs no replacement'), ('replacement_requested', 'Looking for a replacement'), ('replacement_confirmed', 'Replacement confirmed'), ('unfilled', 'No replacement found'), ('withdrawn', 'Withdrawn by the worker')], db_index=True, default='approved', max_length=30)),
                ('replacement_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('resident_responded_at', models.DateTimeField(blank=True, null=True)),
                ('day_rate_paise', models.PositiveIntegerField(default=0)),
                ('forgone_paise', models.PositiveIntegerField(default=0)),
                ('replacement_paise', models.PositiveIntegerField(default=0)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hiring.engagement')),
                ('replacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_assignments', to='workers.workerprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-leave_date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'leave_date'], name='scheduling__status_e18295_idx'), models.Index(fields=['worker', 'leave_date'], name='scheduling__worker__d5b9b2_idx')],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'leave_date'), name='one_leave_request_per_engagement_day'), models.CheckConstraint(condition=models.Q(('replacement', models.F('worker')), _negated=True), name='replacement_is_not_the_absent_worker')],
            },
        ),
    ]
