# Generated by Django 5.2.16 on 2026-08-08 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_servicecategory_bypasses_notice_period'),
        ('hiring', '0002_engagement_last_working_day_and_more'),
        ('scheduling', '0002_leaverequest'),
        ('societies', '0003_resident_average_rating_resident_rating_count_and_more'),
        ('workers', '0003_workerprofile_police_verification_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateField(db_index=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('photo', models.ImageField(blank=True, upload_to='visits/completions/%Y/%m/')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='bookings.booking')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='hiring.engagement')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='societies.society')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-visit_date', '-completed_at'],
                'indexes': [models.Index(fields=['worker', 'visit_date'], name='scheduling__worker__5f4f97_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('engagement__isnull', False)), fields=('engagement', 'visit_date'), name='one_completion_per_engagement_day'), models.UniqueConstraint(condition=models.Q(('booking__isnull', False)), fields=('booking',), name='one_completion_per_booking'), models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', True), ('engagement__isnull', False)), models.Q(('booking__isnull', False), ('engagement__isnull', True)), _connector='OR'), name='completion_belongs_to_exactly_one_visit')],
            },
        ),
    ]
